clients/urls.py
from django.urls import path
from . import views

app_name = 'clients' #es para evitar el conflicto de nombres entre rutas

urlpatterns = [

	path('', views.ClientListView.as_view(), name='client_list'),
	path('crear', views.create, name='create'),
	path('editar/<int:pk>', views.UpdateClient.as_view(), name='edit'),
	path('ver/<int:pk>', views.ClientView.as_view(), name='view'),
	path('search', views.ClientSearchListView.as_view(), name='search'),
]

loans/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'loans' #es para evitar el conflicto de nombres entre rutas

urlpatterns = [

	path('<int:pk>', views.LoansView.as_view(), name='loans_list'),
	path('nuevo_credito',views.create , name='loans_create'),
	#path('crear', views.create, name='create_loan'),
]

prestamista/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [

    path('', views.index, name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('my/', views.my, name='my'),
    path('my/clientes/', include('clients.urls')),
    path('my/clientes/creditos/', include('loans.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.db.models.signals import pre_save
import uuid


class Client(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    document = models.CharField(max_length=8)
    cuil = models.CharField(max_length=13)
    birthday = models.DateField(auto_now=False, null=True, blank=True)
    mobile = models.CharField(max_length=15)
    phone = models.CharField(max_length=15)
    home = models.CharField(max_length=200)
    locality = models.CharField(max_length=100)
    province = models.CharField(max_length=100, default = 'Mendoza')
    postal_code = models.CharField(max_length=4)
    nationality = models.CharField(max_length=100, default='Argentino')
    work = models.CharField(max_length=300)
    work_address = models.CharField(max_length=400)
    work_phone = models.CharField(max_length=15)
    ingresos = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    foto_dni = models.ImageField(upload_to='dni/', null=True, blank=True)
    email = models.EmailField()
    create_at = models.DateTimeField(auto_now= True)
    male_female = models.CharField(max_length=50)
    client_id = models.CharField(max_length=100, null=False, blank= False, unique=True)

    def __str__(self):
        return self.name + ' ' + self.surname

def set_client_id(sender, instance, *args, **kwargs):
    if not instance.client_id:
        instance.client_id = str(uuid.uuid4())


pre_save.connect(set_client_id, sender=Client)

clients/forms.py
from django import forms
from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = [
			'name', 'surname', 'document', 'cuil', 'birthday','mobile','phone',
            'home', 'locality', 'province', 'postal_code', 'nationality', 'work',
            'work_address', 'ingresos', 'foto_dni', 'email', 'male_female'
		]

        labels = {
			'name': 'Nombre',
			'surname': 'Apellido',
			'document': 'DNI',
			'cuil': 'Cuil',
			'birthday': 'Fecha de nacimiento',
			'mobile': 'Celular',
			'phone': 'Telefono fijo',
            'home': 'Domicilio',
            'locality': 'Localidad',
            'province': 'Provincia',
            'postal_code': 'Codigo Postal',
            'nationality': 'Nacionalidad',
            'work': 'Lugar de trabajo',
            'work_address': 'Domicilio laboral',
            'ingresos': 'Ingresos',
            'foto_dni': 'Foto documento',
            'email': 'Correo electronico',
            'male_female':'Genero'
		}


        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','required':'true'}),
            'surname': forms.TextInput(attrs={'class':'form-control','required':'true'}),
            'document': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'8'}),
            'cuil': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'13'}),
            'birthday': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'13','type':'date'}),
            'mobile': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'20'}),
            'phone': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'15'}),
            'nationality': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'25'}),
            'home': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'500'}),
            'locality': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'500'}),
            'postal_code': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'4'}),
            'province': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'7'}),
            'work': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'500'}),
            'work_address': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'500'}),
            'email': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'150','type':'email'}),
            'ingresos': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'150','type':'number'}),
            'male_female': forms.TextInput(attrs={'class':'form-control','required':'true','data-val-length-max':'150','type':'select'}),
        }

clients/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Client
from .forms import ClientForm
from django.urls import reverse_lazy
from django.db.models import Q #para trabajar con una consulta con dist. filtros


class ClientListView(LoginRequiredMixin, ListView):
	login_url = 'login'
	model = Client
	template_name = 'clients/list_client.html'
	paginate_by = 10

	def get_queryset(self):
		return Client.objects.all()


@login_required(login_url='login')
def create(request):
	form = ClientForm(request.POST)#siempre y cuando sea POST
	if request.method == 'POST' and form.is_valid():
		form.save()
		messages.success(request, 'Cliente creado con exito')
		return redirect('clients:client_list')

	return render(request, 'clients/create.html',{
			'form': form
		})

class UpdateClient(LoginRequiredMixin, UpdateView):
	model = Client
	form_class = ClientForm
	template_name = 'clients/create.html'
	success_url = reverse_lazy('clients:client_list')

class ClientView(LoginRequiredMixin, DetailView):
	model = Client
	template_name = 'clients/view.html'


class ClientSearchListView(ListView):
	template_name = 'clients/list_client.html'

	def get_queryset(self):
		#es como poner en sql select * from products like %value% = __icontains
		filters = Q(name__icontains=self.query()) | Q(surname__icontains=self.query())
		return Client.objects.filter(filters)

	def query(self):
		return self.request.GET.get('q')


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['query'] = self.query()
		context['count'] = context['client_list'].count()

		return context

clients/templates/clients/create.html
{% extends 'backend/base-admin.html' %}
{% load static %}


{% block css %}

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}

{% block content %}

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Clientes</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Clientes</a></li>
          <li class="breadcrumb-item active">Crear Clientes</li>
        </ol>

      </div><!-- /.col -->
    </div><!-- /.row -->
    <hr>
  </div><!-- /.container-fluid -->
</div>



  <!-- Main content -->
  <!-- Content Wrapper. Contains page content

  {{ form.username.label_tag }}
  {{ form.username }}

-->

    <!-- Main content -->
    <section class="content">

      <section class="cliente crear">
    <div class="container-fluid">

        <form method="POST">

          {% csrf_token %}


            <fieldset>
                <legend>Datos personales:</legend>
                <div class="row">
                    <div class="col-md-2 text-center">

                        <label class="label" data-toggle="tooltip" title="Agregar foto">
                            <img id="imgAvatar" src="../media/img/no_image.jpg" alt="avatar" width="190px">
                            <input type="file" class="sr-only" id="inputImgAvatar" accept="image/*">
                        </label>
                        <input type="hidden" name="fileAvatarBase64" id="fileAvatarBase64" />
                    </div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-4 col-lg-5">

                                <label class="control-label" for="Nombres">Nombres</label> <span class="text-danger field-validation-valid" data-valmsg-for="Nombres" data-valmsg-replace="true"></span>
                                {{ form.name }}
                                <!-- IDEA: <input class="form-control" required type="text" data-val="true" data-val-length="The field Nombres must be a string with a maximum length of 60." data-val-length-max="60" data-val-required="The Nombres field is required." id="Nombres" name="Nombres" value="" /> -->
                            </div>
                            <div class="col-md-4 col-lg-5">
                                <label class="control-label" for="Apellidos">Apellidos</label> <span class="text-danger field-validation-valid" data-valmsg-for="Apellidos" data-valmsg-replace="true"></span>
                                {{ form.surname }}
                            </div>
                            <div class="col-md-4 col-lg-2">

                                <label class="control-label" for="Sexo">Sexo</label> <span class="text-danger field-validation-valid" data-valmsg-for="Sexo" data-valmsg-replace="true"></span>
                                {{ form.male_female }}
                                <!-- IDEA: <select class="form-control" data-val="true" data-val-maxlength="The field Sexo must be a string or array type with a maximum length of &#x27;2&#x27;." data-val-maxlength-max="2" data-val-required="The Sexo field is required." id="Sexo" name="Sexo"><option value="F">Femenino</option>
<option value="M">Masculino</option>
</select> -->
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12 col-md-4 col-lg-2">
                                <label class="control-label" for="Cedula">Documento Unico</label> <span class="text-danger field-validation-valid" data-valmsg-for="Cedula" data-valmsg-replace="true"></span>
                                {{ form.document }}
                            </div>
                            <div class="col-12 col-md-4 col-lg-2">
                                <label class="control-label" for="Cedula">CUIL</label> <span class="text-danger field-validation-valid" data-valmsg-for="Cedula" data-valmsg-replace="true"></span>
                                {{ form.cuil }}
                            </div>
                            <div class="col-6 col-md-4 col-lg-3">
                                <label class="control-label" for="FechaNacimiento">Fecha Nacimiento</label> <span class="text-danger field-validation-valid" data-valmsg-for="FechaNacimiento" data-valmsg-replace="true"></span>
                                {{ form.birthday }}
                                <!--<input class="form-control" type="date" id="FechaNacimiento" name="FechaNacimiento" value="" />-->
                            </div>
                            <div class="col-6 col-md-4 col-lg-2">
                                <label class="control-label" for="Celular">Celular</label> <span class="text-danger field-validation-valid" data-valmsg-for="Celular" data-valmsg-replace="true"></span>
                                {{ form.mobile }}
                                <!-- IDEA:  <input type="tel" class="form-control" data-val="true" data-val-length="The field Celular must be a string with a maximum length of 20." data-val-length-max="20" data-val-phone="The Celular field is not a valid phone number." id="Celular" name="Celular" value="" />-->
                            </div>
                            <div class="col-6 col-md-4 col-lg-2">
                                <label class="control-label" for="Telefono">Telef&#xF3;no</label> <span class="text-danger field-validation-valid" data-valmsg-for="Telefono" data-valmsg-replace="true"></span>
                                {{ form.phone }}
                            </div>
                            <div class="col-6 col-md-4 col-lg-3">
                                <label class="control-label" for="Nacionalidad">Nacionalidad</label> <span class="text-danger field-validation-valid" data-valmsg-for="Nacionalidad" data-valmsg-replace="true"></span>
                                {{ form.nationality }}
                            </div>
                            <div class="col-6 col-md-4 col-lg-5">
                                <label class="control-label" for="Direccion">Direccion completa</label> <span class="text-danger field-validation-valid" data-valmsg-for="Direccion" data-valmsg-replace="true"></span>
                                {{ form.home }}
                            </div>
                            <div class="col-6 col-md-4 col-lg-3">
                                <label class="control-label" for="Direccion">Localidad</label> <span class="text-danger field-validation-valid" data-valmsg-for="Direccion" data-valmsg-replace="true"></span>
                                {{ form.locality }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">


                    <div class="col-sm-4 col-lg-1">
                        <label class="control-label" for="CodigoPostal">CP</label> <span class="text-danger field-validation-valid" data-valmsg-for="CodigoPostal" data-valmsg-replace="true"></span>
                        {{ form.postal_code }}
                    </div>

                    <div class="col-6 col-sm-4 col-lg-2">
                        <label class="control-label" for="Dependientes">Provincia</label>
                        {{ form.province }}
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4">
                        <label class="control-label" for="Dependientes">Lugar de trabajo</label>
                        {{ form.work }}
                    </div>
                    <div class="col-6 col-sm-4 col-lg-4">
                        <label class="control-label" for="Dependientes">Direccion de trabajo</label>
                        {{ form.work_address }}
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <label class="control-label" for="Email">E-mail</label>
                        {{ form.email }}
                    </div>
                    <div class="col-6 col-md-4 col-lg-2">
                        <label class="control-label" for="TrabajoIngreso">Ingresos</label> <span class="text-danger field-validation-valid" data-valmsg-for="TrabajoIngreso" data-valmsg-replace="true"></span>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>

                                {{ form.ingresos }}
                            </div>
                        </div>
                    </div>

                </div>
            </fieldset>

            <button class="btn btn-primary" type="submit">Crear Cliente</button>
    </form>

    </div>
</section>





    </section>
    <!-- /.content -->

  <!-- /.content-wrapper -->


{% endblock %}

clients/templates/clients/list_client.html
{% extends 'backend/base-admin.html' %}
{% load static %}


{% block css %}

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}

{% block content %}

<!-- IDEA:  <h4 class="text-center">  {{ message }} </h4>-->

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Clientes</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Clientes</a></li>
          <li class="breadcrumb-item active">Listado de clientes</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>



  <!-- Main content -->
  <!-- Content Wrapper. Contains page content -->


    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">


              {% include 'clients/snippets/search.html' with query=query %}
              <br>
              Resultados para: {{ query }}  ( {{ count }} ) Registros


          </h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th>
                          ID
                      </th>
                      <th>
                          DNI
                      </th>
                      <th >
                          Nombre y apellido
                      </th>
                      <th>
                          Localidad
                      </th>
                      <th>
                          Celular
                      </th>
                      <th>
                          Trabajo
                      </th>

                  </tr>
              </thead>
              <tbody>

                {% for clients in object_list %}

                  <tr>
                      <td>
                          {{ clients.id }}
                      </td>
                      <td>
                          {{ clients.document }}
                      </td>
                      <td>
                          {{ clients.name  }} {{ clients.surname  }}
                      </td>
                      <td>
                          {{ clients.locality }}
                      </td>
                      <td>
                        {{ clients.mobile }}
                      </td>
                      <td>
                          {{ clients.work }}
                      </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="{% url 'clients:view' clients.id %}">
                              <i class="fas fa-folder">
                              </i>
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{% url 'clients:edit' clients.id %}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>
                          <a class="btn btn-info btn-sm" href="{% url 'loans:loans_list' clients.id %}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Creditos
                          </a>

                      </td>
                  </tr>


                  {% endfor %}




              </tbody>
          </table>



        </div>


      </div>

  <div id="container-floating">
    <a href="{% url 'clients:create' %}">
        <div id="floating-button" data-toggle="tooltip" data-placement="left" title="Agregar Cliente">
            <div>
                <i class="fas fa-plus-circle fa-4x" size: 5x></i>
            </div>
        </div>
    </a>
  </div>

      <!-- /.card -->

    </section>



    <!-- /.content -->

  <!-- /.content-wrapper -->


{% endblock %}

clients/templates/clients/view.html
{% extends 'backend/base-admin.html' %}
{% load static %}


{% block css %}

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}

{% block content %}

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Clientes</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Clientes</a></li>
          <li class="breadcrumb-item active">Detalle de Clientes</li>
        </ol>

      </div><!-- /.col -->
    </div><!-- /.row -->
    <hr>
  </div><!-- /.container-fluid -->
</div>



  <!-- Main content -->
  <!-- Content Wrapper. Contains page content

  {{ form.username.label_tag }}
  {{ form.username }}

-->

    <!-- Main content -->
    <section class="content">

      <section class="cliente crear">
        <div class="container-fluid">




    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Vista de clientes</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form role="form">
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Nombre y apellido</label>
            <input type="text" class="form-control" id="nombre" value="{{ object.name }}  {{ object.surname }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">DOCUMENTO</label>
            <input type="text" class="form-control" id="documento" value="{{ object.document }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">CUIL</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.cuil }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">FECHA DE NACIMIENTO</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.birthday }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">CELULAR</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.mobile }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">TELEFONO FIJO</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.phone }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">DOMICILIO PERSONAL</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.home }} LOCALIDAD: {{ object.locality }} CP: {{ object.postal_code }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">LUGAR Y DOMICILIO LABORAL</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.work }}, DOMICILIO: {{ object.work_address }} " readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">CORREO ELECTRONICO</label>
            <input type="mail" class="form-control" id="cuil" value="{{ object.email }}" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">INGRESOS</label>
            <input type="text" class="form-control" id="cuil" value="{{ object.ingresos }}" readonly>
          </div>

        <!-- /.card-body -->

        <div class="card-footer">
            <a href="{% url 'clients:client_list' %}" class="btn btn-primary">Volver</a>
            <a href="{% url 'loans:loans_list' %}" class="btn btn-secondary">Ver creditos</a>
            <a href="#" class="btn btn-info">Cobrar una cuota</a>
        </div>
      </form>
    </div>


</section>





    </section>
    <!-- /.content -->

  <!-- /.content-wrapper -->


{% endblock %}